### ISSUE TITLE
 NoMethodError - undefined method `model' for class SolidCache::Entry:

### ISSUE THREAD

**Issue by 34code** [rails/solid_cache#189]
Tried updating from 3x to 4x now getting this error..

**Comment by jwald1** [comment]
I updated from version 0.5.3 to 0.6.0 and I'm experiencing the same error.

**Comment by jwald1** [comment]
The issue appears to be that solid_cache is not yet compatible with Rails 7.2. It works fine with Rails 7.1.

**Comment by djmb** [comment]
Should be fixed in v0.7.0.
